-- V1: Initial schema for ride_booking database
-- Shared by auth-service and user-service

CREATE TABLE IF NOT EXISTS users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name       VARCHAR(255) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    password        VARCHAR(255) NOT NULL,
    role            VARCHAR(255) NOT NULL,
    phone           VARCHAR(255),
    profile_image   VARCHAR(255),

    CONSTRAINT uk_users_email UNIQUE (email)
);
