-- V1: Initial schema for notification-service
-- Database: notification_db

CREATE TABLE IF NOT EXISTS notifications (
    notification_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT,
    ride_id           BIGINT,
    payment_id        BIGINT,
    title             VARCHAR(255),
    message           VARCHAR(1000),
    status            VARCHAR(255),
    created_at        TIMESTAMP,
    sent_at           TIMESTAMP
);

CREATE INDEX idx_notifications_user_id ON notifications(user_id);
CREATE INDEX idx_notifications_ride_id ON notifications(ride_id);
CREATE INDEX idx_notifications_payment_id ON notifications(payment_id);
