-- V1: Initial schema for payment-service
-- Database: payment_db

CREATE TABLE IF NOT EXISTS payments (
    payment_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ride_id           BIGINT,
    user_id           BIGINT,
    amount            DECIMAL(19, 2),
    payment_status    VARCHAR(255),
    payment_method    VARCHAR(255),
    transaction_id    VARCHAR(255),
    payment_time      TIMESTAMP,
    idempotency_key   VARCHAR(255),

    CONSTRAINT uk_payments_idempotency_key UNIQUE (idempotency_key)
);

CREATE TABLE IF NOT EXISTS wallets (
    wallet_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL,
    balance     DECIMAL(19, 2) NOT NULL,

    CONSTRAINT uk_wallets_user_id UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS invoices (
    invoice_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id      BIGINT NOT NULL,
    ride_id         BIGINT,
    user_id         BIGINT,
    amount          DECIMAL(19, 2),
    transaction_id  VARCHAR(255),
    generated_at    TIMESTAMP,

    CONSTRAINT uk_invoices_payment_id UNIQUE (payment_id)
);

CREATE INDEX idx_payments_ride_id ON payments(ride_id);
CREATE INDEX idx_payments_user_id ON payments(user_id);
CREATE INDEX idx_invoices_ride_id ON invoices(ride_id);
CREATE INDEX idx_invoices_user_id ON invoices(user_id);
