-- V1: Initial schema for ride-service
-- Database: ride_service_db

CREATE TABLE IF NOT EXISTS rides (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rider_id          BIGINT NOT NULL,
    driver_id         BIGINT,
    pickup_location   VARCHAR(255) NOT NULL,
    drop_location     VARCHAR(255) NOT NULL,
    pickup_latitude   DOUBLE PRECISION,
    pickup_longitude  DOUBLE PRECISION,
    drop_latitude     DOUBLE PRECISION,
    drop_longitude    DOUBLE PRECISION,
    status            VARCHAR(255) NOT NULL,
    fare              DOUBLE PRECISION,
    requested_at      TIMESTAMP,
    accepted_at       TIMESTAMP,
    started_at        TIMESTAMP,
    completed_at      TIMESTAMP
);

CREATE INDEX idx_rides_rider_id ON rides(rider_id);
CREATE INDEX idx_rides_driver_id ON rides(driver_id);
CREATE INDEX idx_rides_status ON rides(status);
