-- V1: Initial schema for driver-service
-- Database: ride_booking_driver

CREATE TABLE IF NOT EXISTS vehicles (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_number        VARCHAR(255) NOT NULL,
    vehicle_type          VARCHAR(255) NOT NULL,
    vehicle_model         VARCHAR(255) NOT NULL,
    vehicle_color         VARCHAR(255) NOT NULL,
    registration_number   VARCHAR(255) NOT NULL,

    CONSTRAINT uk_vehicles_registration_number UNIQUE (registration_number)
);

CREATE TABLE IF NOT EXISTS drivers (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name            VARCHAR(255) NOT NULL,
    last_name             VARCHAR(255) NOT NULL,
    email                 VARCHAR(255) NOT NULL,
    phone                 VARCHAR(255) NOT NULL,
    license_number        VARCHAR(255) NOT NULL,
    availability_status   VARCHAR(255) NOT NULL DEFAULT 'OFFLINE',
    rating                DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    vehicle_id            BIGINT,
    created_at            TIMESTAMP NOT NULL,
    updated_at            TIMESTAMP,

    CONSTRAINT uk_drivers_email UNIQUE (email),
    CONSTRAINT uk_drivers_phone UNIQUE (phone),
    CONSTRAINT uk_drivers_license_number UNIQUE (license_number),
    CONSTRAINT fk_drivers_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id)
);
